version: "3.8"
services:
    parser:
        build: ./parser/.
        container_name: parser
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - MYSQL_HOST=database
            - MYSQL_PORT=3306
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=database
            - PARSE_TIMEOUT=900
        volumes:
            - ./log:/log
        links:
            - redis
            - database

    tgbot:
        build: ./tgbot/.
        container_name: tgbot
        environment:
            - TOKEN=
            - ADMINS=
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        links:
            - redis

    database:
        image: mariadb
        container_name: database
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=database
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        volumes:
            - ./database/.:/var/lib/mysql
            - ./database/my.ini:/etc/mysql/conf.d/my.cnf
            - ./log/database:/log
        ports:
            - "3306:3306"

    redis:
        image: redis:6.2-alpine
        container_name: redis
        command: redis-server /conf/redis.conf
        volumes:
            - ./redis/redis.ini:/conf/redis.conf
            - ./redis:/data
            - ./log/redis:/log
        ports:
            - "6379:6379"
        restart: always
